version: 2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4-browsers

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rake

  deploy:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    steps:
      - checkout

      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh

      - run:
          name: Publish to Rubygems
          command: |
            gem build timezone_teleporter.gemspec
            gem push "timezone_teleporter-$(git describe --tags | cut -c2-).gem"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
